# Generated by Django 5.0.6 on 2024-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_post_options_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE'),
        ),
    ]
