# Generated by Django 5.0.6 on 2024-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_post_mod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
