# Generated by Django 5.0.6 on 2024-07-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_post_mod_date_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
