# Generated by Django 5.0.6 on 2024-07-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='별점'),
        ),
    ]
