# Generated by Django 5.0.6 on 2024-07-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_review_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Review1',
        ),
    ]
